version: '3.3'

services: 
  java_log_gen:
    build: .
    image: java_log_gen
    container_name: java_log_gen
    restart: on-failure
    volumes:
    - mock_logs:/tmp/mock_logs

  logstash:
    entrypoint: ["echo", "logstash disabled"]
    restart: "no"

secrets:
  filebeat_conf:
    file: ./filebeat_raw.yml
